.TH "TestClass" 3 "test_project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestClass \- Пустой класс для тестирования шаблонных функций  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestClass\fP (int)"
.br
.ti -1c
.RI "int \fBoperator[]\fP (int i)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Пустой класс для тестирования шаблонных функций 

.SH "Author"
.PP 
Generated automatically by Doxygen for test_project from the source code\&.
